/**
 * Prime Perfumes — Tabela de preços do servidor. ARQUIVO GERADO.
 *
 * Não edite à mão: rode "npm run catalogo" depois de alterar os preços no
 * index.html. A chave é "<id do produto>|<tamanho>", exatamente como o
 * carrinho do front-end monta.
 *
 * Gerado a partir de index.html — 33 produtos, 115 variantes.
 */

export const CATALOGO = {
    "armani-my-way-90|90 ml": { nome: "Giorgio Armani My Way (90 ml)", marca: "Giorgio Armani", preco: 899.00 },
    "armani-my-way-90|Decant 10 ml": { nome: "Giorgio Armani My Way (Decant 10 ml)", marca: "Giorgio Armani", preco: 179.80 },
    "armani-my-way-90|Decant 15 ml": { nome: "Giorgio Armani My Way (Decant 15 ml)", marca: "Giorgio Armani", preco: 251.72 },
    "armani-my-way-90|Decant 5 ml": { nome: "Giorgio Armani My Way (Decant 5 ml)", marca: "Giorgio Armani", preco: 98.89 },
    "atheeri|100 ml": { nome: "Lattafa Atheeri (100 ml)", marca: "Lattafa", preco: 354.90 },
    "atheeri|Decant 10 ml": { nome: "Lattafa Atheeri (Decant 10 ml)", marca: "Lattafa", preco: 70.98 },
    "atheeri|Decant 15 ml": { nome: "Lattafa Atheeri (Decant 15 ml)", marca: "Lattafa", preco: 99.37 },
    "atheeri|Decant 5 ml": { nome: "Lattafa Atheeri (Decant 5 ml)", marca: "Lattafa", preco: 39.04 },
    "azzaro-wanted|100 ml": { nome: "Azzaro Wanted (100 ml)", marca: "Azzaro", preco: 890.00 },
    "azzaro-wanted|Decant 10 ml": { nome: "Azzaro Wanted (Decant 10 ml)", marca: "Azzaro", preco: 178.00 },
    "azzaro-wanted|Decant 15 ml": { nome: "Azzaro Wanted (Decant 15 ml)", marca: "Azzaro", preco: 249.20 },
    "azzaro-wanted|Decant 5 ml": { nome: "Azzaro Wanted (Decant 5 ml)", marca: "Azzaro", preco: 97.90 },
    "baccarat-rouge-540-30|30 ml": { nome: "Maison Francis Kurkdjian Baccarat Rouge 540 (30 ml)", marca: "Maison Francis Kurkdjian", preco: 1490.00 },
    "baccarat-rouge-540-30|Decant 10 ml": { nome: "Maison Francis Kurkdjian Baccarat Rouge 540 (Decant 10 ml)", marca: "Maison Francis Kurkdjian", preco: 566.20 },
    "baccarat-rouge-540-30|Decant 15 ml": { nome: "Maison Francis Kurkdjian Baccarat Rouge 540 (Decant 15 ml)", marca: "Maison Francis Kurkdjian", preco: 819.50 },
    "baccarat-rouge-540-30|Decant 5 ml": { nome: "Maison Francis Kurkdjian Baccarat Rouge 540 (Decant 5 ml)", marca: "Maison Francis Kurkdjian", preco: 298.00 },
    "burberry-her-100|100 ml": { nome: "Burberry Her (100 ml)", marca: "Burberry", preco: 849.00 },
    "burberry-her-100|Decant 10 ml": { nome: "Burberry Her (Decant 10 ml)", marca: "Burberry", preco: 169.80 },
    "burberry-her-100|Decant 15 ml": { nome: "Burberry Her (Decant 15 ml)", marca: "Burberry", preco: 237.72 },
    "burberry-her-100|Decant 5 ml": { nome: "Burberry Her (Decant 5 ml)", marca: "Burberry", preco: 93.39 },
    "ch-212-black|100 ml": { nome: "Carolina Herrera 212 VIP Black (100 ml)", marca: "Carolina Herrera", preco: 590.00 },
    "ch-212-black|Decant 10 ml": { nome: "Carolina Herrera 212 VIP Black (Decant 10 ml)", marca: "Carolina Herrera", preco: 118.00 },
    "ch-212-black|Decant 15 ml": { nome: "Carolina Herrera 212 VIP Black (Decant 15 ml)", marca: "Carolina Herrera", preco: 165.20 },
    "ch-212-black|Decant 5 ml": { nome: "Carolina Herrera 212 VIP Black (Decant 5 ml)", marca: "Carolina Herrera", preco: 64.90 },
    "ch-212-men-100|100 ml": { nome: "Carolina Herrera 212 Men (100 ml)", marca: "Carolina Herrera", preco: 549.00 },
    "ch-212-men-100|Decant 10 ml": { nome: "Carolina Herrera 212 Men (Decant 10 ml)", marca: "Carolina Herrera", preco: 109.80 },
    "ch-212-men-100|Decant 15 ml": { nome: "Carolina Herrera 212 Men (Decant 15 ml)", marca: "Carolina Herrera", preco: 153.72 },
    "ch-212-men-100|Decant 5 ml": { nome: "Carolina Herrera 212 Men (Decant 5 ml)", marca: "Carolina Herrera", preco: 60.39 },
    "ch-212-men-200|200 ml": { nome: "Carolina Herrera 212 Men (200 ml)", marca: "Carolina Herrera", preco: 799.00 },
    "ch-212-men-200|Decant 10 ml": { nome: "Carolina Herrera 212 Men (Decant 10 ml)", marca: "Carolina Herrera", preco: 79.90 },
    "ch-212-men-200|Decant 15 ml": { nome: "Carolina Herrera 212 Men (Decant 15 ml)", marca: "Carolina Herrera", preco: 111.86 },
    "ch-212-men-200|Decant 5 ml": { nome: "Carolina Herrera 212 Men (Decant 5 ml)", marca: "Carolina Herrera", preco: 43.95 },
    "fakhar-extrait|100 ml": { nome: "Lattafa Fakhar Extrait (100 ml)", marca: "Lattafa", preco: 219.90 },
    "fakhar-extrait|Decant 10 ml": { nome: "Lattafa Fakhar Extrait (Decant 10 ml)", marca: "Lattafa", preco: 43.98 },
    "fakhar-extrait|Decant 15 ml": { nome: "Lattafa Fakhar Extrait (Decant 15 ml)", marca: "Lattafa", preco: 61.57 },
    "fakhar-extrait|Decant 5 ml": { nome: "Lattafa Fakhar Extrait (Decant 5 ml)", marca: "Lattafa", preco: 24.19 },
    "goodgirl-edp-100|80 ml": { nome: "Carolina Herrera Good Girl (80 ml)", marca: "Carolina Herrera", preco: 729.00 },
    "goodgirl-edp-100|Decant 10 ml": { nome: "Carolina Herrera Good Girl (Decant 10 ml)", marca: "Carolina Herrera", preco: 145.80 },
    "goodgirl-edp-100|Decant 15 ml": { nome: "Carolina Herrera Good Girl (Decant 15 ml)", marca: "Carolina Herrera", preco: 204.12 },
    "goodgirl-edp-100|Decant 5 ml": { nome: "Carolina Herrera Good Girl (Decant 5 ml)", marca: "Carolina Herrera", preco: 80.19 },
    "hawas-black|100 ml": { nome: "Rasasi Hawas Black (100 ml)", marca: "Rasasi", preco: 219.90 },
    "hawas-black|Decant 10 ml": { nome: "Rasasi Hawas Black (Decant 10 ml)", marca: "Rasasi", preco: 43.98 },
    "hawas-black|Decant 15 ml": { nome: "Rasasi Hawas Black (Decant 15 ml)", marca: "Rasasi", preco: 61.57 },
    "hawas-black|Decant 5 ml": { nome: "Rasasi Hawas Black (Decant 5 ml)", marca: "Rasasi", preco: 24.19 },
    "invictus-edp|100 ml": { nome: "Paco Rabanne Invictus (100 ml)", marca: "Paco Rabanne", preco: 779.00 },
    "invictus-edp|Decant 10 ml": { nome: "Paco Rabanne Invictus (Decant 10 ml)", marca: "Paco Rabanne", preco: 155.80 },
    "invictus-edp|Decant 15 ml": { nome: "Paco Rabanne Invictus (Decant 15 ml)", marca: "Paco Rabanne", preco: 218.12 },
    "invictus-edp|Decant 5 ml": { nome: "Paco Rabanne Invictus (Decant 5 ml)", marca: "Paco Rabanne", preco: 85.69 },
    "jadore-edp-200|100 ml": { nome: "Dior J'adore (100 ml)", marca: "Dior", preco: 1090.00 },
    "jadore-edp-200|Decant 10 ml": { nome: "Dior J'adore (Decant 10 ml)", marca: "Dior", preco: 218.00 },
    "jadore-edp-200|Decant 15 ml": { nome: "Dior J'adore (Decant 15 ml)", marca: "Dior", preco: 305.20 },
    "jadore-edp-200|Decant 5 ml": { nome: "Dior J'adore (Decant 5 ml)", marca: "Dior", preco: 119.90 },
    "khamrah|100 ml": { nome: "Lattafa Khamrah (100 ml)", marca: "Lattafa", preco: 174.90 },
    "khamrah|Decant 10 ml": { nome: "Lattafa Khamrah (Decant 10 ml)", marca: "Lattafa", preco: 31.48 },
    "khamrah|Decant 15 ml": { nome: "Lattafa Khamrah (Decant 15 ml)", marca: "Lattafa", preco: 44.07 },
    "khamrah|Decant 5 ml": { nome: "Lattafa Khamrah (Decant 5 ml)", marca: "Lattafa", preco: 17.32 },
    "kit-hawas-oud-khamrah|Kit 3 x 100 ml": { nome: "Kit Promoção da Semana (Kit 3 x 100 ml)", marca: "Prime Perfumes", preco: 486.90 },
    "kit-khamrah-fakhar-hawas|Kit 3 x 100 ml": { nome: "Kit Promoção da Semana (Kit 3 x 100 ml)", marca: "Prime Perfumes", preco: 537.30 },
    "la-vie-est-belle-200|100 ml": { nome: "Lancôme La Vie Est Belle (100 ml)", marca: "Lancôme", preco: 849.00 },
    "la-vie-est-belle-200|Decant 10 ml": { nome: "Lancôme La Vie Est Belle (Decant 10 ml)", marca: "Lancôme", preco: 169.80 },
    "la-vie-est-belle-200|Decant 15 ml": { nome: "Lancôme La Vie Est Belle (Decant 15 ml)", marca: "Lancôme", preco: 237.72 },
    "la-vie-est-belle-200|Decant 5 ml": { nome: "Lancôme La Vie Est Belle (Decant 5 ml)", marca: "Lancôme", preco: 93.39 },
    "le-male-edp|125 ml": { nome: "Jean Paul Gaultier Le Male (125 ml)", marca: "Jean Paul Gaultier", preco: 640.80 },
    "le-male-edp|200 ml": { nome: "Jean Paul Gaultier Le Male (200 ml)", marca: "Jean Paul Gaultier", preco: 890.00 },
    "le-male-edp|Decant 10 ml": { nome: "Jean Paul Gaultier Le Male (Decant 10 ml)", marca: "Jean Paul Gaultier", preco: 89.00 },
    "le-male-edp|Decant 15 ml": { nome: "Jean Paul Gaultier Le Male (Decant 15 ml)", marca: "Jean Paul Gaultier", preco: 124.60 },
    "le-male-edp|Decant 5 ml": { nome: "Jean Paul Gaultier Le Male (Decant 5 ml)", marca: "Jean Paul Gaultier", preco: 48.95 },
    "miss-dior-edp|100 ml": { nome: "Dior Miss Dior (100 ml)", marca: "Dior", preco: 990.00 },
    "miss-dior-edp|Decant 10 ml": { nome: "Dior Miss Dior (Decant 10 ml)", marca: "Dior", preco: 198.00 },
    "miss-dior-edp|Decant 15 ml": { nome: "Dior Miss Dior (Decant 15 ml)", marca: "Dior", preco: 277.20 },
    "miss-dior-edp|Decant 5 ml": { nome: "Dior Miss Dior (Decant 5 ml)", marca: "Dior", preco: 108.90 },
    "onemillion-edp|100 ml": { nome: "Paco Rabanne 1 Million (100 ml)", marca: "Paco Rabanne", preco: 820.00 },
    "onemillion-edp|Decant 10 ml": { nome: "Paco Rabanne 1 Million (Decant 10 ml)", marca: "Paco Rabanne", preco: 164.00 },
    "onemillion-edp|Decant 15 ml": { nome: "Paco Rabanne 1 Million (Decant 15 ml)", marca: "Paco Rabanne", preco: 229.60 },
    "onemillion-edp|Decant 5 ml": { nome: "Paco Rabanne 1 Million (Decant 5 ml)", marca: "Paco Rabanne", preco: 90.20 },
    "orientica-royal-amber-150|150 ml": { nome: "Orientica Royal Amber (150 ml)", marca: "Orientica", preco: 649.00 },
    "orientica-royal-amber-150|80 ml": { nome: "Orientica Royal Amber (80 ml)", marca: "Orientica", preco: 402.38 },
    "orientica-royal-amber-150|Decant 10 ml": { nome: "Orientica Royal Amber (Decant 10 ml)", marca: "Orientica", preco: 86.32 },
    "orientica-royal-amber-150|Decant 15 ml": { nome: "Orientica Royal Amber (Decant 15 ml)", marca: "Orientica", preco: 120.71 },
    "orientica-royal-amber-150|Decant 5 ml": { nome: "Orientica Royal Amber (Decant 5 ml)", marca: "Orientica", preco: 47.38 },
    "orientica-royal-amber-80|80 ml": { nome: "Orientica Royal Amber (80 ml)", marca: "Orientica", preco: 439.00 },
    "orientica-royal-amber-80|Decant 10 ml": { nome: "Orientica Royal Amber (Decant 10 ml)", marca: "Orientica", preco: 96.58 },
    "orientica-royal-amber-80|Decant 15 ml": { nome: "Orientica Royal Amber (Decant 15 ml)", marca: "Orientica", preco: 135.21 },
    "orientica-royal-amber-80|Decant 5 ml": { nome: "Orientica Royal Amber (Decant 5 ml)", marca: "Orientica", preco: 53.12 },
    "oudforglory|100 ml": { nome: "Lattafa Oud For Glory (100 ml)", marca: "Lattafa", preco: 154.90 },
    "oudforglory|Decant 10 ml": { nome: "Lattafa Oud For Glory (Decant 10 ml)", marca: "Lattafa", preco: 27.88 },
    "oudforglory|Decant 15 ml": { nome: "Lattafa Oud For Glory (Decant 15 ml)", marca: "Lattafa", preco: 39.03 },
    "oudforglory|Decant 5 ml": { nome: "Lattafa Oud For Glory (Decant 5 ml)", marca: "Lattafa", preco: 15.34 },
    "paradoxe-200|100 ml": { nome: "Prada Paradoxe (100 ml)", marca: "Prada", preco: 989.00 },
    "paradoxe-200|Decant 10 ml": { nome: "Prada Paradoxe (Decant 10 ml)", marca: "Prada", preco: 197.80 },
    "paradoxe-200|Decant 15 ml": { nome: "Prada Paradoxe (Decant 15 ml)", marca: "Prada", preco: 276.92 },
    "paradoxe-200|Decant 5 ml": { nome: "Prada Paradoxe (Decant 5 ml)", marca: "Prada", preco: 108.79 },
    "sabah-al-ward-sugar|100 ml": { nome: "Al Wataniah Sabah Al Ward Sugar (100 ml)", marca: "Al Wataniah", preco: 229.90 },
    "sabah-al-ward-sugar|Decant 10 ml": { nome: "Al Wataniah Sabah Al Ward Sugar (Decant 10 ml)", marca: "Al Wataniah", preco: 45.98 },
    "sabah-al-ward-sugar|Decant 15 ml": { nome: "Al Wataniah Sabah Al Ward Sugar (Decant 15 ml)", marca: "Al Wataniah", preco: 64.37 },
    "sabah-al-ward-sugar|Decant 5 ml": { nome: "Al Wataniah Sabah Al Ward Sugar (Decant 5 ml)", marca: "Al Wataniah", preco: 25.29 },
    "sauvage-edp-200|100 ml": { nome: "Dior Sauvage (100 ml)", marca: "Dior", preco: 834.00 },
    "sauvage-edp-200|200 ml": { nome: "Dior Sauvage (200 ml)", marca: "Dior", preco: 1390.00 },
    "sauvage-edp-200|Decant 10 ml": { nome: "Dior Sauvage (Decant 10 ml)", marca: "Dior", preco: 139.00 },
    "sauvage-edp-200|Decant 15 ml": { nome: "Dior Sauvage (Decant 15 ml)", marca: "Dior", preco: 194.60 },
    "sauvage-edp-200|Decant 5 ml": { nome: "Dior Sauvage (Decant 5 ml)", marca: "Dior", preco: 76.45 },
    "scandal-intense|80 ml": { nome: "Jean Paul Gaultier Scandal Intense (80 ml)", marca: "Jean Paul Gaultier", preco: 890.00 },
    "scandal-intense|Decant 10 ml": { nome: "Jean Paul Gaultier Scandal Intense (Decant 10 ml)", marca: "Jean Paul Gaultier", preco: 178.00 },
    "scandal-intense|Decant 15 ml": { nome: "Jean Paul Gaultier Scandal Intense (Decant 15 ml)", marca: "Jean Paul Gaultier", preco: 249.20 },
    "scandal-intense|Decant 5 ml": { nome: "Jean Paul Gaultier Scandal Intense (Decant 5 ml)", marca: "Jean Paul Gaultier", preco: 97.90 },
    "sebastian-dark-oil-kit|Kit 1 L": { nome: "Sebastian Dark Oil Kit (Kit 1 L)", marca: "Sebastian", preco: 494.00 },
    "sebastian-mascara-dark-oil|250 ml": { nome: "Sebastian Máscara Dark Oil (250 ml)", marca: "Sebastian", preco: 185.40 },
    "sebastian-mascara-dark-oil|500 ml": { nome: "Sebastian Máscara Dark Oil (500 ml)", marca: "Sebastian", preco: 309.00 },
    "sospiro-vibrato|100 ml": { nome: "Sospiro Vibrato (100 ml)", marca: "Sospiro", preco: 1690.00 },
    "sospiro-vibrato|Decant 10 ml": { nome: "Sospiro Vibrato (Decant 10 ml)", marca: "Sospiro", preco: 338.00 },
    "sospiro-vibrato|Decant 15 ml": { nome: "Sospiro Vibrato (Decant 15 ml)", marca: "Sospiro", preco: 473.20 },
    "sospiro-vibrato|Decant 5 ml": { nome: "Sospiro Vibrato (Decant 5 ml)", marca: "Sospiro", preco: 185.90 },
    "vs-splash-bare-vanilla|250 ml": { nome: "Victoria's Secret Bare Vanilla (250 ml)", marca: "Victoria's Secret", preco: 149.00 },
    "vs-splash-midnight-bloom|250 ml": { nome: "Victoria's Secret Midnight Bloom (250 ml)", marca: "Victoria's Secret", preco: 149.00 },
    "vs-splash-pure-seduction|250 ml": { nome: "Victoria's Secret Pure Seduction (250 ml)", marca: "Victoria's Secret", preco: 149.00 }
};
